runtime: python39

instance_class: F1

handlers:
- url: /image
  static_dir: static/image

- url: /
  static_files: www/index.html
  upload: www/index.html

env_variables:
  BUCKET_NAME: "profileappp"
